spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: com.rocha.app.dto
    datasource:
    database: ${MYSQL_DATABASE:product}
    host: ${MYSQL_HOST:localhost}
    port: ${MYSQL_PORT:3307}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_ROOT_PASSWORD:123456}
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Bogota

  jpa:
    database: mysql 
    #show-sql: true 
    hibernate:
      ddl-auto: update
server:
  port: 8282            